### ISSUE TITLE
Weird glitches with end of string characters

### ISSUE THREAD

**Issue by lepinekong** [octref/polacode#119] opened 2019-09-01 15:57 UTC
Hello,

I have these weird glitches on VSCode

Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

![code-plugin](https://user-images.githubusercontent.com/5175342/64078983-db45bf80-cce1-11e9-8520-655ce607f17e.png)

**Comment by GeroCoded** [comment] 2019-09-02 20:26
I think this is the same Issue as [Issue #109 ](https://github.com/octref/polacode/issues/109)

**Comment by octref** [comment] 2019-09-24 17:24
Duplicate of #109.

**Closed by octref** 2019-09-24 17:24 UTC
